openapi: 3.0.1
info:
  title: API de Pets
  version: v1
servers:
  - url: http://localhost:8080
    description: API para gerenciamento de pets
paths:
  /pet:
    get:
      summary: Listar todos os pets
      tags:
        - pet-controller
      operationId: findAll
      responses:
        '200':
          description: Lista de pets retornada com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      summary: Criar um novo pet
      tags:
        - pet-controller
      operationId: save
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Pet criado com sucesso
        '400':
          description: Erro na requisição
  /pet/{id}:
    get:
      summary: Buscar pet por ID
      tags:
        - pet-controller
      operationId: findById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Pet encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet não encontrado
    put:
      summary: Substituir pet por ID
      tags:
        - pet-controller
      operationId: replacePet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Pet substituído com sucesso
        '404':
          description: Pet não encontrado
    patch:
      summary: Atualizar parcialmente um pet
      tags:
        - pet-controller
      operationId: updatePet
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Pet atualizado com sucesso
        '404':
          description: Pet não encontrado
    delete:
      summary: Deletar pet por ID
      tags:
        - pet-controller
      operationId: deleteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: Pet deletado com sucesso
        '404':
          description: Pet não encontrado
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nome:
          type: string
        especie:
          type: string
        idade:
          type: integer
          format: int32
